Repository CodebilityDev/codebility-plus, pull requests merged in 2024-10, with the labels that each got.

#71 Codebility | CODEB-3 : Settings-Roles
  apps/codebility/Components/modals/AddRoleModal.tsx
  apps/codebility/Components/modals/DeleteRoleModal.tsx
  apps/codebility/Components/modals/EditRoleModal.tsx
  apps/codebility/app/home/settings/roles/_components/role-container.tsx
  apps/codebility/app/home/settings/roles/_components/role-list-table-desktop.tsx
  apps/codebility/app/home/settings/roles/_components/role-list-table-mobile.tsx
  apps/codebility/app/home/settings/roles/_components/role-list-table.tsx
  apps/codebility/app/home/settings/roles/_types/roles.ts
  apps/codebility/app/home/settings/roles/action.ts
  apps/codebility/app/home/settings/roles/components/RoleListsTable.tsx
  apps/codebility/app/home/settings/roles/page.tsx
  packages/ui/src/dialog.tsx
Labels: bug, ready for merge in main

#86 Codebility | CODEB-2 : Intern's Page/Screen
  apps/codebility/app/(marketing)/_components/landing/landing-admin-card.tsx
  apps/codebility/app/home/interns/_components/intern-card.tsx
  apps/codebility/app/home/interns/_components/intern-container.tsx
  apps/codebility/app/home/interns/_components/intern-list.tsx
  apps/codebility/app/home/interns/_components/interns-filter.tsx
  apps/codebility/app/home/interns/_types/intern.ts
  apps/codebility/app/home/interns/data.ts
  apps/codebility/app/home/interns/page.tsx
Labels: dont merge

#98 CODEB-44 | Add Project Partners
  apps/codebility/app/(marketing)/_components/landing/landing-partners.tsx
  apps/codebility/app/(marketing)/page.tsx
  apps/codebility/public/assets/images/partners/bradwell.png
  apps/codebility/public/assets/images/partners/federal-plans.png
  apps/codebility/public/assets/images/partners/genius-web-services.png
  apps/codebility/public/assets/images/partners/infraspan.png
  apps/codebility/public/assets/images/partners/netmedia.png
  apps/codebility/public/assets/images/partners/travel-tribe.png
  apps/codebility/public/assets/images/partners/zwift-tech.png
Labels: ready for merge in main

#108 CODEBILITY | CODEB-59 Add new partnerships logo
  apps/codebility/app/(marketing)/_components/landing/landing-partners.tsx
  apps/codebility/public/assets/images/partners/ai.png
  apps/codebility/public/assets/images/partners/averps.png
  apps/codebility/public/assets/images/partners/bradwell.png
  apps/codebility/public/assets/images/partners/federal-plans.png
  apps/codebility/public/assets/images/partners/genius-web-services.png
  apps/codebility/public/assets/images/partners/infraspan.png
  apps/codebility/public/assets/images/partners/netmedia.png
  apps/codebility/public/assets/images/partners/travel-tribe.png
  apps/codebility/public/assets/images/partners/zwift-tech.png
Labels: ready for merge in main

#95 CODEB-27 | Implement Account Settings Page with 2FA, Password Change, and Account Deletion
  apps/codebility/app/home/_components/home-navbar.tsx
  apps/codebility/app/home/account-settings/_components/account-settings-2FA.tsx
  apps/codebility/app/home/account-settings/_components/account-settings-backdrop.tsx
  apps/codebility/app/home/account-settings/_components/account-settings-change-password.tsx
  apps/codebility/app/home/account-settings/_components/account-settings-delete.tsx
  apps/codebility/app/home/account-settings/_components/account-settings-dialog.tsx
  apps/codebility/app/home/account-settings/_components/account-settings-header.tsx
  apps/codebility/app/home/account-settings/page.tsx
  apps/codebility/app/home/settings/resume/_components/resume-personal-info.tsx
  apps/codebility/middleware.ts
  apps/codebility/schema/account-settings-zod.ts
Labels: ready for merge in main

#106 Codebility | CODEB-40 In-House Page Unhandled Runtime Error
  apps/codebility/app/home/layout.tsx
  apps/codebility/lib/server/codev.service.ts
Labels: ready for merge in main

#99 Codebility | CODEB-26 Marketing Page - Feature: Profile Dropdown
  apps/codebility/Components/modals/ProjectAddModal.tsx
  apps/codebility/app/(marketing)/_components/marketing-navigation-main.tsx
  apps/codebility/app/(marketing)/_components/marketing-navigation.tsx
Labels: ready for merge in main

#114 Codebility | CODEB-49 : Accepted Application Routing
  apps/codebility/app/authv2/sign-in/_components/sign-in-form.tsx
  apps/codebility/app/home/_components/home-toast-notification.tsx
  apps/codebility/app/home/layout.tsx
Labels: ready for merge in main
